version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/source
    depends_on:
      - phpfpm
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="password"
      # - MYSQL_DATABASE=[MYDATABASE]
      # - MYSQL_USER=[MYUSER]
      # - MYSQL_PASSWORD=[MYPASSWORD]
    volumes:
      - mysqldata:/var/lib/db
  
  phpfpm:
    build: docker-images/phpfpm
    # ports:
    #   - "9000:9000"
    volumes:
      - ./conf/phpfpm/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      - ./conf/phpfpm/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
      - ./source:/var/www/source

volumes:
  mysqldata: